### ISSUE TITLE
graphics trails when using opengl CS (Retroarch)

### ISSUE THREAD

**Issue by ghost** [FCare/Kronos#1452]
hello, i get graphics trails all over the screen when using opengl CS, making games unplayable

![Street Fighter Alpha 2 Gold-230225-121149](https://user-images.githubusercontent.com/14978933/221356197-1db28ced-fd35-41f7-9bfb-96edc7cd5462.png)

if i use standard opengl mode then the games are really stuttery 

i don't get any of these problems with yabause 

thank you

**Comment by fafling** [comment]
Which game is it exactly ?

**Comment by ghost** [comment]
I put the screenshot, can't you see!? Street fighter alpha 2 gold but I'm sure it's happening on lots of games. I cannot get Kronos to run properly at all no matter which settings I try

**Comment by fafling** [comment]
OK so this is in fact Street fighter collection disc 2, thanks for the guessing game.

The sprites trails are visible from the beginning of the demo loop after the the loading screen. There is no workaround.

The issue occurs in both video cores in public v2.5.0. It can't be checked in the last WIP (syncTiming 4b32c86) due to a black screen.

It appears in the 1st WIP of fbaccess branch (commit c114701) on Jan 28. The preceding Jan 25 extui-align WIP (e8acba4) doesn't have this issue.

The sprites aren't erased on the upper 3 quarters of the screen. A polygon at the beginning of the drawing list of VDP1 erases the lower part. The upper part should be erased by the vblank erase, because the game sets FBCR at 0x3 and TVMR at 0x8.

Tested with the US redump.

**Comment by ghost** [comment]
sorry i thought you could tell which game it was

so does that mean it won't be fixed?

**Comment by fafling** [comment]
Well it's a regression that should be fixed eventually.
For the time being, if you want to play this game in Kronos, you can use the preceding version, v2.3.1.

**Comment by ghost** [comment]
i'm wanting to use it in retroarch though

**Comment by Immersion95** [comment]
This also happens on SFA1/2/3 and Super Puzzle Fighter. I built the latest core and it still happens on Puzzle Fighter, the other games had the black screen which I can't move past.

**Comment by fafling** [comment]
Fixed by [ea0eace](https://github.com/FCare/Kronos/commit/ea0eaceb0f9523ff350d4d8e2a8861991ccc16d0).
